version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musnote
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

